### PR TITLE
Try building on Win64; add license info and more maintainers.

### PR DESCRIPTION
**Pull request by cbrueffer**
@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by cbrueffer** [comment]
@conda-forge-admin, please rerender

**Comment by jdblischak** [comment]
Thanks for working on this, @cbrueffer!

igraph lists the following system requirements:

> SystemRequirements: gmp (optional), libxml2 (optional), glpk (optional)

gmp and libxml2 are already being installed, so you could try adding `{{native}}glpk` as a dependency.

**Comment by jdblischak** [comment]
Actually, even if adding glpk doesn't fix the problem with Windows, then we should add it in a separate PR. I just had a colleague run into problems with igraph on our compute cluster due to glpk.

**Comment by cbrueffer** [comment]
The compile problems look unrelated to glpk, so I'd be surprised if that helped here. Haven't had time to dig into this more unfortunately.

**Comment by bgruening** [comment]
@conda-forge-admin, please rerender

**Comment by bgruening** [comment]
@conda-forge-admin, please rerender

**Comment by bgruening** [comment]
@conda-forge-admin, please update for conda-build 3

**Comment by bgruening** [comment]
```
<command-line>:0:22: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token
igraph_interrupt_internal.h:42:8: note: in expansion of macro 'IGRAPH_THREAD_LOCAL'
 extern IGRAPH_THREAD_LOCAL igraph_interruption_handler_t
```

This one is blocking https://github.com/conda-forge/r-mrmre-feedstock/pull/1

**Comment by cbrueffer** [comment]
Obsoleted by #6

**Pull request closed without merging**
