### PR TITLE
add GLPK support

### LINKED ISSUE #29: GLPK should be a dependency
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

GLPK should be a dependency. Without it, some functionality is disabled, for example:

```
> g <- sample_gnm(10,20,directed=T)
> cluster_optimal(g)
Error in cluster_optimal(g) : 
  At core/community/optimal_modularity.c:87 : GLPK is not available, Unimplemented function call
```

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

### PR DESCRIPTION
**Pull request by szhorvat**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #29.

### CODE REVIEW

**Comment by szhorvat** [comment]
@conda-forge-admin, please rerender

**Comment by szhorvat** [comment]
Looking at the CI logs, this now does pick up GLPK on Linux and macOS, but not on Windows, and I'm not yet sure why. @philip-khor some help would be appreciated here, as I'm not really familiar with conda-forge. Even without Windows support, this would be a welcome improvement.

**Comment by szhorvat** [comment]
@conda-forge-admin, please rerender

**Comment by szhorvat** [comment]
@conda-forge-admin, please rerender

**Comment by szhorvat** [comment]
Regarding GMP, linking to an external GMP library brings no benefits _at this moment_ (but neither does it hurt). The vendored mini-GMP is perfectly fine. So don't spend time on that specific issue.

**Comment by szhorvat** [comment]
Since you're looking at igraph-feedstock, I'll include @vtraag here. But note that there's an important difference. igraph's C core is normally build using CMake. R/igraph uses autotools. This means that they don't use the same mechanisms to discover dependencies such as GLPK. CMake tends to be better at this ...

**Comment by szhorvat** [comment]
You can see that it doesn't pick up GLPK here:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=517508&view=logs&j=5be07ae1-d8ba-5406-47b6-8e3a3a12f825&t=0bf03e01-0bec-5b85-5316-b1633322e895&l=531

```
checking for glp_read_mps in -lglpk... no
```

Perhaps it can only discover GLPK from msys2? But when I used `{{ native }}glpk`, it said that it can't find a resolution for `m2w64-glpk`. Perhaps with >= 4.57 that's fixed?

**Comment by philip-khor** [comment]
> Looking at the CI logs, this now does pick up GLPK on Linux and macOS, but not on Windows, and I'm not yet sure why. @philip-khor some help would be appreciated here, as I'm not really familiar with conda-forge. Even without Windows support, this would be a welcome improvement.

Let's wrap up this PR for non-Win builds and perhaps address the Win builds in a separate PR, dropping glpk dependencies for the Win builds. Would you like to add yourself as a maintainer for this recipe as well?

**Comment by szhorvat** [comment]
> Let's wrap up this PR for non-Win builds and perhaps address the Win builds in a separate PR

Sounds good, and thanks for the help!

> Would you like to add yourself as a maintainer for this recipe as well?

I'd rather not, as I rarely use R, and I never use R from conda. I simply wanted to make sure that people who want to use R/igraph from conda get a good experience. But I would not be comfortable taking responsibility for a piece of software (or distribution) that I do not regularly use myself.

**Comment by philip-khor** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
